devsearch/urls.py
import imp
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include("projects.urls")), #empty string that triggers the root domain
    path('',include("users.urls")) #anything that starts with users go to this users.urls file
    #and the user app (urls.py) takes care of routing from there
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
#we have created this file 
from django.urls import URLPattern, path
from . import views

# . means from this app or main folder 


urlpatterns = [
    path('',views.profiles, name="profiles"), #root domain (don't give space between the empty bracket)
    path('profile/<str:pk>/',views.userProfile,name="user-profile")
]

projects/models.py
from email.policy import default
from statistics import mode
from django.db import models
import uuid
from users.models import Profile

# Create your models here.


class Project(models.Model):
    owner = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    featured_image = models.ImageField(null=True,blank=True,default="default.jpg")
    demo_link = models.CharField(max_length=2000,null=True,blank=True)
    source_link = models.CharField(max_length=2000,null=True,blank=True)
    tag = models.ManyToManyField('Tag',blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,editable=False,primary_key=True)
    def __str__(self) :
        return self.title

class Review(models.Model):
    VOTE_TYPE = (
        ('up','Up Vote'),
        ('down','Down Vote')
    )
    project= models.ForeignKey(Project,on_delete=models.CASCADE) #CASCADE will delete all reviews if project is deleted
    body = models.TextField(null=True,blank=True)
    value=models.CharField(max_length=200,choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,editable=False,primary_key=True)
    def __str__(self) :
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,editable=False,primary_key=True)
    def __str__(self) :
        return self.name

users/models.py
from distutils.command.upload import upload
import email
from email.policy import default
import imp
import uuid
from pyexpat import model
from tkinter import CASCADE
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE, null=True, blank=True) #this create a one to one relationship bewteen django default user model to profile model 
    #one to one means (1 user 1 profile linked) & (1 profile 1 user linked) whenever a new user created in user modeldb then a profile is created from where we can extract the user info to and make our profile model.
    name = models.CharField(max_length=200,null=True,blank=True)
    email=models.EmailField(max_length=500,null=True,blank=True)
    username =models.CharField(max_length=200,null=True,blank=True)
    location =models.CharField(max_length=200,null=True,blank=True)
    short_intro = models.CharField(max_length=200,null=True,blank=True)
    bio= models.TextField(null=True,blank=True)
    profile_image = models.ImageField(null=True,blank=True,upload_to='profiles/',default='profiles/user-default.png')
    social_github = models.CharField(max_length=200,null=True,blank=True)
    social_linkedin = models.CharField(max_length=200,null=True,blank=True)
    social_twitter = models.CharField(max_length=200,null=True,blank=True)
    social_website = models.CharField(max_length=200,null=True,blank=True)
    social_quora = models.CharField(max_length=200,null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,editable=False,primary_key=True)
    def __str__(self):
        return str(self.user.username)
    
class Skill(models.Model):
    owner= models.ForeignKey(Profile,on_delete=models.CASCADE)
    name=models.CharField(max_length=200,null=True,blank=True)
    description= models.TextField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,editable=False,primary_key=True)
    def __str__(self):
        return str(self.name)

users/views.py
from multiprocessing import context
from django.shortcuts import render
from .models import Profile
# Create your views here.
#after creating the template for this app now we create function based view

def profiles(request):
    profiles=Profile.objects.all() #taking all the profiles in database (as structured as model and pass as context dictionary to the template to render it)
    context={
        "profiles":profiles,
    }
    return render(request,"users/profiles.html",context)




def userProfile(request,pk):
    profile= Profile.objects.get(id=pk) #get method gives a single data depending upon the condition written inside the get () here we want the profile having id = pk i.e grab the profile we selected/clicked upon
    topSkills= profile.skill_set.exclude(description__exact="") # (modelname)_set is the way to access the data of its child models
    otherSkills = profile.skill_set.filter(description="")
    context={
        "profile":profile,
        "topSkills":topSkills,
        "otherSkills":otherSkills
    }
    return render(request,"users/user-profile.html",context)
    #by passsing context(bunch of datas ), it is now available to the template we are sending it
 #and from there we can grab the datas from db.
# users/profiles.html this is the template name we want to render via a function profiles
# after this create a file of url to add a path to the views

users/templates/users/profiles.html
{% extends "main.html" %} {% block content %}
<main class="home">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
        <h2>FROM AROUND THE WORLD</h2>
      </div>

      <div class="hero-section__search">
        <form class="form" action="#" method="get">
          <div class="form__field">
            <label for="formInput#search">Search Developers </label>
            <input
              class="input input--text"
              id="formInput#search"
              type="text"
              name="text"
              placeholder="Search by developer name"
            />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="devlist">
    <div class="container">
      <div class="grid grid--three">
        {% for profile in profiles%}
        <div class="column card">
          <div class="dev">
            <a href="{% url 'user-profile' profile.id %}" class="card__body">
              <div class="dev__profile">
                <img
                  class="avatar avatar--md"
                  src="{{profile.profile_image.url}}"
                  alt="image"
                />
                <div class="dev__meta">
                  <h3>{{profile.name}}</h3>
                  <h5>{{profile.short_intro|slice:"60"}}</h5>
                </div>
              </div>
              <p class="dev__info">{{profile.bio|slice:"150"}}</p>
              <div class="dev__skills">
                <!-- (skill is the model name of the child and profile is parent ) -->
                {% for skill in profile.skill_set.all|slice:"5" %}
                <span class="tag tag--pill tag--main">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</main>
{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %} {% block content %}

<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img
              class="avatar avatar--xl"
              src="{{ profile.profile_image.url }}"
            />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro}}</p>
            <p class="dev__location">Based in {{profile.location}}</p>
            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a
                  title="Github"
                  href="{{ profile.social_github }}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_quora %}
              <li>
                <a
                  title="Stackoverflow"
                  href="{{ profile.social_quora }}"
                  target="_blank"
                  ><i class="im im-stackoverflow"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_twitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{ profile.social_twitter }}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_linkedin %}
              <li>
                <a
                  title="LinkedIn"
                  href="{{ profile.social_linkedin }}"
                  target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_website %}
              <li>
                <a
                  title="Personal Website"
                  href="{{ profile.social_website }}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
            <a href="#" class="btn btn--sub btn--lg">Send Message </a>
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{profile.bio}}</p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            <!-- for taking data from its children inside the parent  -->
            {% for skill in topSkills %}
            <div class="devSkill">
              <h4 class="devSkill__title">{{skill.name}}</h4>
              <p class="devSkill__info">{{skill.description}}</p>
            </div>
            {% endfor%}

            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
              {% for skill in otherSkills %}
              <span class="tag tag--pill tag--sub tag--lg">
                <small>{{skill.name}}</small>
              </span>
              {% endfor%}
            </div>
          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Projects</h3>
          <div class="grid grid--two">
            {% for project in profile.project_set.all %}
            <div class="column">
              <div class="card project">
                <a href="{% url 'greet' project.id %}" class="project">
                  <img
                    class="project__thumbnail"
                    src="{{project.featured_image.url}}"
                    alt="project thumbnail"
                  />
                  <div class="card__body">
                    <h3 class="project__title">{{project.title}}</h3>
                    <p>
                      <a
                        class="project__author"
                        href="{% url 'user-profile' profile.id %}"
                        >{{project.owner.name}}</a
                      >
                    </p>
                    <!-- we are extracting data from parent from child -->
                    <p class="project--rating">
                      <span style="font-weight: bold"
                        >{{project.vote_ratio}}%</span
                      >
                      Postitive Feedback ({{project.vote_total}}
                      Vote{{project.vote_total|pluralize:"s"}})
                    </p>
                    <div class="project__tags">
                      <!-- we have many to many relationship soo we have to access tag in below way rather than (model_set) (one to many) -->
                      {% for tag in project.tag.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{tag}}</small>
                      </span>
                      {% endfor %}
                    </div>
                  </div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}